### ISSUE TITLE
Support of "appearance"

### ISSUE THREAD

**Issue by refactorraccoon** [postcss/autoprefixer-core#14]
if you'll create style:

```
select {
    appearence: none;
}
```

it doesn't add any styles with prefixes, but according to http://caniuse.com/#search=appearance it should

**Comment by simevidas** [comment]
FYI `appearance: none` has been accepted by the CSS WG, [source](http://www.w3.org/blog/CSS/2015/04/15/minutes-telecon-244/). It has already been added to the CSS UI L4 editor’s draft: [Chapter 8](http://dev.w3.org/csswg/css-ui-4/#form-styling).

**Comment by yisibl** [comment]
+1

**Comment by ai** [comment]
Nice news. I will add it to 5.2.

**Comment by TrySound** [comment]
Uu-hu!

**Comment by fvsch** [comment]
Simple question on scope. If I want to remove the arrow thing on `<select>` elements, I can use `-prefix-appearance:none` on WebKit/Blink and Firefox, but IE 10+ needs `select::-ms-expand {display: none;}`.

My understanding is that Autoprefixer would add moz and webkit prefixes for the appearance property, but will not add the IE-specific code since a) it differs significantly and b) there is no way to detect that `appearance:none` was used on a selector targetting a select element. Is that correct?

**Comment by ai** [comment]
@fvsch yeap, `select::-ms-expand` is not a task for Autoprefixer.

**Comment by ai** [comment]
Becuase `appearance` with `auto` and `none` [became a standard](http://www.w3.org/blog/CSS/2015/04/15/minutes-telecon-244/) again, Autoprefixer 5.2 will have `appearance` support.

**Comment by TrySound** [comment]
@fvsch You can write own processor for this task.
