### ISSUE TITLE
Publish standalone version on bower

### ISSUE THREAD

**Issue by unindented** [postcss/autoprefixer-core#2]
Would it be possible to build the standalone version of `autoprefixer` on every release, and add a `bower.json` manifest, so that `autoprefixer` can be consumed as a bower dependency?

Thank you in advance.

**Comment by jproffitt3ge** [comment]
Wanted to note there is a valid use case for a packaged standalone / browser compatible version. I'm developing a web app for creating `<style>` elements from LESS stylesheets. We write content for many different platforms that all have their own css quirks. We end up writing and rewriting a lot of boiler plate css that'd be better expressed as a base stylesheet with configurable parameters like "gutter-width", "...-font-size" and "accent-color".

Right now the entire app works in browser and can even be cached for offline use. There is no backend to worry about. In order to add Autoprefixer, I would need to write and spin up a whole node backend.

Edit: Turns out webpack can package the node version such that it can run in browser. Wow! This makes the standalone package moot, and invalidates this use case.

**Comment by ai** [comment]
@jproffitt3ge why you can’t use webpack or browserify to pack npm modules in your project bundle?

**Comment by jproffitt3ge** [comment]
@ai I can, I discovered that shortly after making that comment. My apologies. I was going to delete my comment, but then decided I should leave it in case anyone else stumbles onto it and doesn't know webpack can actually do this.
